### ISSUE TITLE
Weird issue when compiling from source

### ISSUE THREAD

**Issue by vrrdnt** [canyonmodded/canyon#49] opened 2021-02-10 18:57 UTC
When I compile canyon from source, using the commands from README.md, I get this error: [pastebin.com/0Qquwbgw](https://pastebin.com/0Qquwbgw).  
"zip END header not found" is the most common reason for each error, and I'm unsure how to go about fixing that.  
Any help would be appreciated!

**Comment by KoboDev** [comment] 2021-02-10 19:32
You downloaded the Source instead of cloning using git?
That'll probably be the reason why it fails to compile. (For me it couldn't find the .git despite downloading it?)
I also compiled freshly with maven to make sure that wasn't borked also.
(I am Using Maven-3.6.3 to compile, also I used JDK8 to compile.)

**Comment by Titaniumtown** [comment] 2021-02-24 05:00
I can reproduce this issue, even with openjdk 8, clearing my maven cache, and cloning the repo. And I'm on linux.

**Comment by KoboDev** [comment] 2021-06-09 02:10
Closing this, Its been fixed for a while and should be working.
Before I go you should update your Dependencies by deleting your .m2 folder.
It has been fixed for a way too long time, and i've may never really actually updated people here on github.

**Closed as completed by KoboDev** 2021-06-09 02:10 UTC
Labels: bug
